trigger: none
pool: 
  name: agent1
steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'newsc'
    backendAzureRmResourceGroupName: 'saurabh-rg'
    backendAzureRmStorageAccountName: 'sgtsaurabh'
    backendAzureRmContainerName: 'newcont'
    backendAzureRmKey: '
  - task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'newsc'
    backendAzureRmResourceGroupName: 'saurabh-rg'
    backendAzureRmStorageAccountName: 'sgtsaurabh'
    backendAzureRmContainerName: 'newcont'
    backendAzureRmKey: 'prod.terraform.tfstate''
  
  